# ── .gitlab-ci.yml ──────────────────────────────
# 所有 Job 都继承相同的基础镜像、缓存与变量
default:
  image: python:3.11-slim
  cache:
    paths:
      - .cache/pip                       # 加速 pip install
  variables:
    # 供 Django / psycopg2 解析
    DB_NAME: sportsdb
    DB_USER: sportsuser
    DB_PASS: sportspwd
    DB_HOST: postgres
    DB_PORT: "5432"
    SECRET_KEY: "django-insecure-ci-only"

stages:
  - lint      # flake8
  - test      # pytest

############################
# 1) flake8 代码规范检查   #
############################
flake8:
  stage: lint
  before_script:
    - pip install --upgrade pip
    - pip install -r requirements.txt
  script:
    - flake8 backend
  allow_failure: true        # 若仅警告可不阻塞 CI
  artifacts:
    when: always
    expire_in: 1 week
    paths:
      - flake-report.html    # 若用 flake8-html 可输出报告
  tags: []                   # 如学校 Runner 有 tag 填这里

############################
# 2) pytest 单元测试       #
############################
pytest:
  stage: test
  services:
    - name: postgres:15
      alias: postgres
      variables:
        POSTGRES_DB: $DB_NAME
        POSTGRES_USER: $DB_USER
        POSTGRES_PASSWORD: $DB_PASS
  before_script:
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - python backend/manage.py migrate --noinput
  script:
    - pytest
  artifacts:
    when: always
    expire_in: 1 week
    reports:
      junit: junit-report.xml
    paths:
      - htmlcov/               # pytest-cov 生成的覆盖率报告
