name: sports_booking_app
description: A sports booking application with a modern design.
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # ──────────── UI & Icons ────────────
  cupertino_icons: ^1.0.5
  google_fonts:    ^6.2.0
  flutter_rating_bar: ^4.0.1    # ⭐ star-rating widget (restored)

  # ──────────── Networking & State ────────────
  dio: ^5.4.0                # HTTP client
  flutter_dotenv: ^5.0.2     # load .env
  flutter_riverpod: ^2.5.1   # state-management / DI
  flutter_secure_storage: ^9.0.0  # secure token storage
  google_sign_in: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/         # load entire folder
    - .env
