name: sports_booking_app
description: A sports booking application with a modern design.
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^4.0.3
  provider: ^6.1.3
  flutter_rating_bar: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/badminton.jpg
    - assets/images/bungee.jpg
    - assets/images/cycling.jpg
    - assets/images/sailing.jpg
    - assets/images/hero_banner.jpg
    - assets/images/kayaking.jpg
    - assets/images/mountain_biking.jpg
    - assets/images/paragliding.jpg
