# Generated by Django 5.2.3 on 2025-07-16 15:47

import django.contrib.gis.db.models.fields
import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sports", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30, unique=True)),
                ("icon", models.CharField(blank=True, max_length=100)),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.AlterField(
            model_name="slot",
            name="sport",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="slots",
                to="sports.sport",
            ),
        ),
        migrations.CreateModel(
            name="Facility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("location", django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ("radius", models.PositiveIntegerField(default=1000)),
                (
                    "categories",
                    models.ManyToManyField(
                        related_name="facilities", to="sports.category"
                    ),
                ),
            ],
        ),
        migrations.AlterUniqueTogether(
            name="slot",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="slot",
            name="facility",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="slots",
                to="sports.facility",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="slot",
            unique_together={("facility", "begins_at")},
        ),
        migrations.AddIndex(
            model_name="facility",
            index=django.contrib.postgres.indexes.GistIndex(
                fields=["location"], name="sports_faci_locatio_675843_gist"
            ),
        ),
    ]
