# Generated by Django 5.2.3 on 2025-08-10 12:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_organization"),
        ("sports", "0018_activity_organization"),
    ]

    operations = [
        migrations.CreateModel(
            name="PriceRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weekday",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(6),
                        ]
                    ),
                ),
                ("time_start", models.TimeField()),
                ("time_end", models.TimeField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=7)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="booking",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name="slot",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="activity",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activities",
                to="accounts.organization",
            ),
        ),
        migrations.AlterField(
            model_name="slot",
            name="sport",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="slots",
                to="sports.sport",
            ),
        ),
        migrations.AddIndex(
            model_name="slot",
            index=models.Index(
                fields=["activity", "begins_at"], name="sports_slot_activit_44ef9d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="slot",
            index=models.Index(
                fields=["activity", "ends_at"], name="sports_slot_activit_c49aca_idx"
            ),
        ),
        migrations.AddField(
            model_name="pricerule",
            name="activity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="price_rules",
                to="sports.activity",
            ),
        ),
        migrations.AddIndex(
            model_name="pricerule",
            index=models.Index(
                fields=["activity", "weekday", "time_start", "time_end"],
                name="sports_pric_activit_594d97_idx",
            ),
        ),
    ]
