# Generated by Django 5.2.3 on 2025-08-10 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_organization'),
        ('sports', '0018_activity_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='organization',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.CASCADE,
                related_name='activities',
                to='accounts.organization',
            ),
        ),
        migrations.AlterField(
            model_name='slot',
            name='sport',
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=models.CASCADE,
                related_name='slots',
                to='sports.sport',
            ),
        ),
        migrations.AddIndex(
            model_name='slot',
            index=models.Index(fields=['activity', 'begins_at'], name='sports_slot_activit_44ef9d_idx'),
        ),
        migrations.AddIndex(
            model_name='slot',
            index=models.Index(fields=['activity', 'ends_at'], name='sports_slot_activit_c49aca_idx'),
        ),
    ]
