# Generated by Django 5.2.3 on 2025-08-12 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sports", "0019_slot_is_active_alter_activity_organization_and_more"),
        ("sports", "0020_booking_status_choices"),
    ]

    operations = []
